# Generated by Django 5.1 on 2024-09-02 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
